spring:
  jpa:
    show-sql: false
    hibernate:
      naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: validate
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql:///<GCP_MYSQL_DATABASE_NAME>?cloudSqlInstance=<GCP_MYSQL_INSTANCE_CONNECTION_NAME>&socketFactory=com.google.cloud.sql.mysql.SocketFactory
    username: <GCP_MYSQL_DATABASE_USERNAME>
    password: <GCP_MYSQL_DATABASE_PASSWORD>
    hikari.data-source-properties:
      useSSL: true
      useUnicode: true
      socketTimeout: 1800000
      connectTimeout: 10000
      characterEncoding: utf8
      allowPublicKeyRetrieval: true
      jdbcCompliantTruncation: false
      createDatabaseIfNotExist: true
  liquibase:
    enabled: true
    drop-first: false
  cloud:
    gcp.sql:
      enabled: false

server:
  port: 8080
  servlet.session.timeout: 1800
  tomcat.accesslog.enabled: true
